<?php

namespace AlexanderC\Bundle\UngaBungaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationData
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationData extends EntityRepository
{
}
