parameters:
#    unga_bunga.example.class: AlexanderC\Bundle\UngaBungaBundle\Example

services:
#    unga_bunga.example:
#        class: %unga_bunga.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
