customer:
    pattern:  /
    defaults: { _controller: "UngaBungaBundle:Customer:index" }

customer_show:
    pattern:  /{id}/show
    defaults: { _controller: "UngaBungaBundle:Customer:show" }

customer_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UngaBungaBundle:Customer:delete" }


